name: Representing characters
attire:
  active: Letters
blocks:
  disabled: [ ]
  visible: [ "COMMANDS"   , "Poner", "Mover", "Sacar", "IrAlBorde"
                          , "Built-in procedures", "My procedures"
                          , "RepeticionSimple", "RepeticionCondicional"
                          , "AlternativaSimple", "AlternativaCompleta"
           , "EXPRESSIONS", "Color", "Direccion", "Numero"
                          , "nroBolitas", "hayBolitas", "puedeMover"
                          , "OperadorNumerico", "OperadorDeComparacion", "OperadorOpuesto"
                          , "OperadorLogico", "OperadorDeNegacion"
           , "DEFINITIONS", "DefinicionDeProcedimientoSimple", "DefinicionDeFuncionSimpleDeclarativa"
           ]
execution_speed:
  active: high


inherit:
  $course: gobstonescourses/courseDemo 
  $assets:
    extra: true
    attires:
     - Letters
  blocks:
    defaultToolbox: true
  board: true
  attire:
    user_permissions: true
    visible: true
  execution_speed:
    user_permissions: true
  library: true