name: About compression of information
attire:
  active: RGB Colors
  visible: false
blocks:
  disabled: [ ]
  visible: [ "COMMANDS"   , "Poner", "Mover", "Sacar", "IrAlBorde"
                          , "Built-in procedures", "My procedures"
                          , "RepeticionSimple", "RepeticionCondicional"
                          , "AlternativaSimple", "AlternativaCompleta"
           , "EXPRESSIONS", "Color", "Direccion", "Numero"
                          , "nroBolitas", "hayBolitas", "puedeMover"
                          , "OperadorNumerico", "OperadorDeComparacion", "OperadorOpuesto"
                          , "OperadorLogico", "OperadorDeNegacion"
           , "DEFINITIONS", "DefinicionDeProcedimientoSimple", "DefinicionDeFuncionSimpleDeclarativa"
           ]
board:
  user_permissions:
    can_change_initial_board: true
execution_speed:
  active: instantaneous

inherit:
  $course: gobstonescourses/courseDemo 
  $assets:
    extra: true
  blocks:
    defaultToolbox: true
  board:
    active: true
    initial_board_source: true
    visible_edition: true
    collapse_toolbox: true
    user_permissions:
      can_view_attire_section: true
      can_edit_board: true
      can_change_initial_board_source: true
      can_view_size_section: true
  attire:
    user_permissions: true
  execution_speed:
    user_permissions: true
  library: true