name: Snake
attire:
  active: Snake
blocks:
  disabled: []
  visible: [ "COMMANDS"   , "Poner", "Mover", "Sacar", "IrAlBorde", "VaciarTablero"
                          , "Built-in procedures", "My procedures"
                          , "RepeticionSimple", "RepeticionCondicional"
                          , "AlternativaSimple", "AlternativaCompleta"
                          , "Asignacion"
           , "EXPRESSIONS", "Color", "Direccion", "Numero"
                          , "nroBolitas", "hayBolitas", "puedeMover"
                          , "Built-in functions", "My functions"
                          , "OperadorNumerico", "OperadorDeComparacion", "OperadorOpuesto"
                          , "OperadorLogico", "OperadorDeNegacion"
                          , "siguiente", "previo", "opuesto"
           , "DEFINITIONS", "procedures_defnoreturn", "DefinicionDeFuncionDeclarativa"
                          , "InteractiveProgram"
                          , "InteractiveLetterBinding", "InteractiveNumberBinding", "InteractiveKeyBinding"
           ]
board:
  initial_board_source: random
  user_permissions:
    can_change_initial_board: true
execution_speed:
  active: instantaneous

inherit:
  $course: gobstonescourses/courseDemo 
  $assets:
    extra: true
    attires:
     - Snake
  blocks:
    defaultToolbox: true
  board: 
    active: true
    visible_edition: true
    collapse_toolbox: true
    user_permissions:
      can_view_attire_section: true
      can_edit_board: true
      can_change_initial_board_source: true
      can_view_size_section: true
  attire:
    user_permissions: true
    visible: true
  execution_speed:
    user_permissions: true
  library: true