name: Converting images to grayscale
attire:
  active: RGB Colors
blocks:
  disabled: [ ]
  visible: [ "COMMANDS"   , "Poner", "Mover", "Sacar", "IrAlBorde"
                          , "Built-in procedures", "My procedures"
                          , "RepeticionSimple", "RepeticionCondicional"
                          , "AlternativaSimple", "AlternativaCompleta"
           , "EXPRESSIONS", "Color", "Direccion", "Numero"
                          , "nroBolitas", "hayBolitas", "puedeMover"
                          , "OperadorNumerico", "OperadorDeComparacion", "OperadorOpuesto"
                          , "OperadorLogico", "OperadorDeNegacion"
           , "DEFINITIONS", "procedures_defnoreturnnoparams", "DefinicionDeFuncionSimpleDeclarativa"
           ]
board:
  user_permissions:
    can_change_initial_board: true
    can_change_initial_board_source: true
execution_speed:
  active: instantaneous
  user_permissions:
    can_change_speed: true

inherit:
  $course: gobstonescourses/courseDemo 
  $assets:
    extra: true
    attires:
     - RGB Colors
  blocks:
    defaultToolbox: true
  board:
    active: true
    initial_board_source: true
    visible_edition: true
    collapse_toolbox: true
    user_permissions:
      can_view_attire_section: true
      can_edit_board: true
      can_view_size_section: true
  attire:
    user_permissions: true
  execution_speed:
    user_permissions: true
  library: true