name: 'The farmer, the teacher, and the gobstones'
attire:
  active: Planting tomatoes
blocks:
  disabled: [ "Poner", "Sacar", "Mover", "IrAlBorde"
            ]
  visible:  [ "COMMANDS", "Poner", "Sacar", "Mover", "IrAlBorde"
                        , "Built-in procedures", "My procedures"   
            , "DEFINITIONS", "procedures_defnoreturnnoparams"
            ]

inherit:
  $course: gobstonescourses/courseDemo 
  $assets:
    extra: true
  #  attires:
  #    - Squares
  blocks:
    defaultToolbox: true
  execution_speed: true
  library: true
  board: true
  attire:
    user_permissions: true
    visible: true