name: 'The farmer, the teacher, and the gobstones'
attire:
  active: Planting tomatoes
  user_permissions:
    can_toggle_visibility: true
  visible: true
blocks:
  disabled: []
  visible: [ "COMMANDS" ]
board:
  active: 1
  initial_board_source: selected
  visible_edition: true
  collapse_toolbox: false
  user_permissions:
    can_view_attire_section: true
    can_edit_board: false
    can_change_initial_board: false
    can_change_initial_board_source: false
    can_view_size_section: false
execution_speed:
  active: medium
  user_permissions:
    can_change_speed: true
library:
  visible: false

inherit:
  $course: gobstonescourses/courseDemo # (Opcional) Es para que si abre el proyecto solo le muestre un cartel de "Este ejercicio no te va a andar a menos que estés en el curso tal"
  $assets:
    extra: true
  #  attires:
  #    - Squares
  # -----------------------------------------------------------------
  # De acá en adelante se puede poner cualquier fragmento de meta.yml
  # para complementar cualquier propiedad que no esté definida acá...
  # -----------------------------------------------------------------
  blocks:
    defaultToolbox: true