name: 'The farmer, the teacher, and the gobstones'
attire:
  active: Planting tomatoes
blocks:
  disabled: [ "Poner", "Sacar", "Mover", "IrAlBorde"
            ]
  visible:  [ "COMMANDS"
            , "Poner", "Sacar", "Mover", "IrAlBorde"
            , "Primitive procedures"
            , "My procedures"
            ]

inherit:
  $course: gobstonescourses/courseDemo # (Opcional) Es para que si abre el proyecto solo le muestre un cartel de "Este ejercicio no te va a andar a menos que estés en el curso tal"
  $assets:
    extra: true
  #  attires:
  #    - Squares
  # -----------------------------------------------------------------
  # De acá en adelante se puede poner cualquier fragmento de meta.yml
  # para complementar cualquier propiedad que no esté definida acá...
  # -----------------------------------------------------------------
  blocks:
    defaultToolbox: true
  execution_speed: true
  library: true
  board: true
  attire:
    user_permissions: true
    visible: true