name: Binary numbers, procedurally
attire:
  active: null
  visible: false
blocks:
  disabled: [ "Poner", "Sacar", "IrAlBorde"
            , "RepeticionSimple"
            , "Color", "Numero"
            ]
  visible: [ "COMMANDS"   , "Poner", "Mover", "Sacar", "IrAlBorde"
                          , "Built-in procedures", "My procedures"
                          , "RepeticionSimple"
           , "EXPRESSIONS", "Color", "Direccion", "Numero"
           , "DEFINITIONS", "procedures_defnoreturnnoparams"
           ]
board:
  visible_edition: false
execution_speed:
  active: high

inherit:
  $course: gobstonescourses/courseDemo 
  $assets:
    extra: true
  blocks:
    defaultToolbox: true
  board:
    active: true
    initial_board_source: true
    collapse_toolbox: false
    user_permissions: true
  attire:
    user_permissions: true
  execution_speed:
    user_permissions: true
  library: true
